[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["Pool"]
solc = "0.8.15"
optimizer = true
optimizer_runs = 200
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[fmt]
line_length = 120
